version: "3.5"

services:
  app:
    build: .
    container_name: medical-center-api
    restart: unless-stopped
    env_file:
      - .env
    ports: 
      - 3000:3000
    links: 
     - mysql
    depends_on:
      - mysql
    networks:
      - app-network
  mysql: 
    container_name: medical-center
    restart: always
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
    - "3306:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge